export type BridgeProgress = any;
export const BRIDGE_TOKENS: any = [];
export const commitmentHex: any = () => '';
export const createBridgeNote: any = () => {};
export type LightClientHead = any;
export const lockOnL1: any = () => {};
export const readIsBridged: any = () => {};
export const readLightClientHead: any = () => {};
export const requestBridgeIn: any = () => {};
export const sepoliaTxUrl: any = () => '';
export const stellarContractUrl: any = () => '';
